#' Process SIM
#'
#' @param data Raw SIM data generated by the function download.SIM with all columns.
#'
#' @returns
#' @export
#'
#' @examples
process.SIM <- function(data) {
  require(dplyr)
  require(lubridate)

  # Data Processing +++++++++++++++++++++++++++++++++++++++++++++++++++++++
  SIM <- data

  # Removing 'CONTADOR' column (count column, not necessary for analysis)
  SIM =
    SIM %>%
    select(-CONTADOR, ESTABDESCR)

  # Creating 'Óbito fetal e até 11 meses' column (column name "Óbito fetal e até 11 meses," counts the number of deaths in this category)
  SIM$`Obito fetal e até 11 meses` <- NA


  # Replace only the second "*" with "|"
  for (coluna in colnames(SIM)) {
    if (grepl("^LINHA", coluna)) {
      SIM[[coluna]] <- gsub("^(.*?\\*.*?\\*)", "\\1|", SIM[[coluna]])
    }
  }

  # Replace the remaining "*"
  for (coluna in colnames(SIM)) {
    SIM[[coluna]] <- gsub("\\*", "", SIM[[coluna]])
  }

  SIM$TERM <- sub("X", "", SIM$LINHAA)

  SIM$TERM <- sub("\\|.*", "", SIM$TERM)

  # Inserting external files for decoding ++++++++++++++++++++++++++++

  # Add the folder that contains CBO (Classificação Brasileira de Ocupações/Brazilian Classification of Occupations),
  #CID (Classificação Internacional de Doenças/International Classification of Diseases), and Municipalities


  SIM$IDADEINT <- c()

  if (any(!grepl("^\\d{3}$", SIM$IDADE))) {
    SIM$IDADEINT <- NA  # Retorna NA para códigos inválidos
  }


  # Extrair a unidade e a quantidade
  unidade <- substr(as.character(SIM$IDADE), 1, 1)
  quantidade <- as.numeric(substr(as.character(SIM$IDADE), 2, 3))

  SIM$IDADEINT <- ifelse(SIM$IDADE == "999", NA,
                         ifelse(unidade == "4", quantidade,
                                ifelse(as.numeric(as.character(SIM$IDADE))<=400, 0,
                                       ifelse(unidade == "5", quantidade + 100, 0))))

  SIM <- SIM %>%
    mutate(TIPOBITO=recode(TIPOBITO,`1`="Fetal",`2`="Não Fetal"),

           SEXO=recode(SEXO,`1`="Masculino",`2`="Feminino",`0`="Ignorado", `9`="Ignorado"),

           RACACOR=recode(RACACOR,`1`="Branca",`2`="Preta",`3`="Amarela",`4`="Parda",`5`="Indígena"),

           ESTCIV=recode(ESTCIV,`1`="Solteiro",`2`="Casado",`3`="Viúvo",`4`="Separado judicialmente/divorciado",`5`="União estável",`9`="Ignorado"),

           ESC2010=recode(ESC2010,`0`="Sem escolaridade",`1`="Fundamental I (1ª a 4ª série)",`2`="Fundamental II (5ª a 8ª série)",
                          `3`="Médio (antigo 2º Grau)",`4`="Superior incompleto",`5`="Superior completo",`9`="Ignorado"),

           LOCOCOR=recode(LOCOCOR,`1`="Hospital",`2`="Outros estabelecimentos de saúde",`3`="domicílio",`4`="via pública",`5`="outros",
                          `6`="Aldeia indígena",`9`="Ignorado"),

           ESCMAE2010=recode(ESCMAE2010,`0`="Sem escolaridade",`1`="Fundamental I (1ª a 4ª série)",`2`="Fundamental II (5ª a 8ª série)",
                             `3`="Médio (antigo 2º Grau)",`4`="Superior incompleto",`5`="Superior completo",`9`="Ignorado"),

           QTDFILVIVO=recode(QTDFILVIVO,`99`=NA_character_, .default = QTDFILVIVO),

           QTDFILMORT=recode(QTDFILMORT,`99`=NA_character_, .default = QTDFILMORT),

           SEMAGESTAC=recode(SEMAGESTAC,`99`=NA_character_, .default = SEMAGESTAC),

           GRAVIDEZ=recode(GRAVIDEZ,`1`="Única",`2`="Dupla",`3`="Tripla ou mais",`9`="Ignorado"),

           PARTO=recode(PARTO,`1`="Vaginal",`2`="Cesáreo",`9`="Ignorado"),

           OBITOPARTO=recode(OBITOPARTO,`1`="Antes",`2`="Durante",`3`="Depois",`9`="Ignorado"),

           TPMORTEOCO=recode(TPMORTEOCO,`1`="Na gravidez",`2`="No parto",`3`="No abortamento",`4`="Até 42 dias após o término do parto",`5`="de 43 dias a 1 ano após o término da gestação",
                             `8`="não ocorreu nestes períodos",`9`="Ignorado"),

           ASSISTMED=recode(ASSISTMED,`1`="Sim",`2`="Não",`9`="Ignorado"),

           NECROPSIA=recode(NECROPSIA,`1`="Sim",`2`="Não",`9`="Ignorado"),

           CIRCOBITO=recode(CIRCOBITO,`1`="Acidente",`2`="Suicídio",`3`="Homicídio",`4`="Outros",`5`="Ignorado"),

           ACIDTRAB=recode(ACIDTRAB,`1`="Sim",`2`="Não",`9`="Ignorado"),

           FONTE=recode(FONTE,`1`="Ocorrência policial",`2`="Hospital",`3`="Família",`4`="Outra",`5`="Ignorado"),

           ESC=recode(ESC, `0`="Nenhuma",`1`="Nenhuma",`2`="1 a 3 anos",`3`="4 a 7 anos",`4`="8 a 11 anos",`5`="12 e mais",`9`="Ignorado"),

           ESCMAE=recode(ESCMAE, `0`="Nenhuma",`1`="Nenhuma",`2`="1 a 3 anos",`3`="4 a 7 anos",`4`="8 a 11 anos",`5`="12 e mais",`9`="Ignorado"),

           GESTACAO=recode(GESTACAO,`1`="Menos de 22 semanas",`2`="22 a 27 semanas",`3`="28 a 31 semanas",`4`="32 a 36 semanas",
                           `5`="37 a 41 semanas",`6`="42 semanas e mais",`9`="Ignorado"),

           OBITOGRAV=recode(OBITOGRAV,`1`="Sim",`2`="Não",`9`="Ignorado"),

           OBITOPUERP=recode(OBITOPUERP,`1`="Sim, ate 42 dias",`2`="Sim, de 43 dias a 01 ano",`3`="Não",`9`="Ignorado"),

           EXAME=recode(EXAME,`1`="Sim",`2`="Não",`9`="Ignorado"),

           CIRURGIA=recode(CIRURGIA,`1`="Sim",`2`="Não",`9`="Ignorado"),

           TPPOS=recode(TPPOS,`1`="Sim",`2`="Não",`9`="Ignorado"),

           ATESTANTE=recode(ATESTANTE,`1`="Sim",`2`="Substituto",`3`="IML",`4`="SVO",`5`="Outros",`9`="Ignorado"),

           FONTEINV=recode(FONTEINV,`1`="Comitê de Morte Materna e/ou Infantil",`2`="Visita domiciliar / Entrevista família",
                           `3`="Estab Saúde / Prontuário",`4`="Relacion com outros bancos de dados",`5`="SVO",`6`="IML",`7`="Outra fonte",
                           `8`="Múltiplas fontes",`9`="Ignorado"),

           ESCMAEAGR1=recode(ESCMAEAGR1,`00`="Sem Escolaridade",`01`="Fundamental I Incompleto",`02`="Fundamental I Completo",
                             `03`="Fundamental II Incompleto",`04`="Fundamental II Completo",`05`="Ensino Médio Incompleto",
                             `06`="Ensino Médio Completo",`07`="Superior Incompleto",`08`="Superior Completo",`09`="Ignorado",
                             `10`="Fundamental I Incompleto ou Inespecífico",`11`="Fundamental II Incompleto ou Inespecífico",
                             `12`="Ensino Médio Incompleto ou Inespecífico"),

           ESCFALAGR1=recode(ESCFALAGR1,`00`="Sem Escolaridade",`01`="Fundamental I Incompleto",`02`="Fundamental I Completo",
                             `03`="Fundamental II Incompleto",`04`="Fundamental II Completo",`05`="Ensino Médio Incompleto",
                             `06`="Ensino Médio Completo",`07`="Superior Incompleto",`08`="Superior Completo",`09`="Ignorado",
                             `10`="Fundamental I Incompleto ou Inespecífico",`11`="Fundamental II Incompleto ou Inespecífico",
                             `12`="Ensino Médio Incompleto ou Inespecífico"),

           STDOEPIDEM=recode(STDOEPIDEM,`1`="Sim",`2`="Não",`9`="Ignorado"),

           STDONOVA=recode(STDONOVA,`1`="Sim",`2`="Não",`9`="Ignorado"),

           TPOBITOCOR=recode(TPOBITOCOR,`1`="Durante a gestação",`2`=" Durante o abortamento",`3`="Após o abortamento",
                             `4`="No parto ou até 1 hora após o parto",`5`="No puerpério -até 42 dias após o parto",
                             `6`="Entre 43 dias e até 1 ano após o parto",`7`="A investigação não identificou o momento do óbito",
                             `8`="Mais de um ano após o parto",`9`="O óbito não ocorreu nas circunstanciasanteriores"),

           ESCFALAGR1=recode(ESCFALAGR1,`01`="Não acrescentou nem corrigiu informação",`02`="Sim, permitiu o resgate de novas informações",
                             `03`="Sim, permitiu a correção de alguma das causas informadas originalmente"),

           TPNIVELINV=recode(TPNIVELINV,`E`="Estadual",`R`="Regional",`M`="Municipal"),

           MORTEPARTO=recode(MORTEPARTO,`1`="Antes",`2`="Durante",`3`="Após",`9`="Ignorado"),

           ALTCAUSA=recode(ALTCAUSA,`1`="Sim",`2`="Não",`9`="Ignorado"),

           DTOBITO=dmy(DTOBITO),

           HORAOBITO=paste0(substr(HORAOBITO,1,2),":", substr(HORAOBITO,3,4)),

           DTNASC=dmy(DTNASC),

           DTCADASTRO=dmy(DTCADASTRO),

           IDADE=as.numeric(as.character(IDADE)),

           IDADEMAE=as.numeric(as.character(IDADEMAE)),

           QTDFILVIVO=as.numeric(as.character(QTDFILVIVO)),

           QTDFILMORT=as.numeric(as.character(QTDFILMORT)),

           PESO=as.numeric(as.character(PESO)),

           SERIESCFAL=as.numeric(as.character(SERIESCFAL)),

           SERIESCMAE=as.numeric(as.character(SERIESCMAE)),

           SEMAGESTAC=as.numeric(as.character(SEMAGESTAC))
    )

  SIM <- data.frame(lapply(SIM, function(x) if (is.factor(x)) as.character(x) else x))

  SIM <- SIM %>%
    mutate(CODUFRES = substring(CODMUNRES,1,2))

  SIM <- SIM %>%
    mutate(CODUFNATU = substring(CODMUNNATU,1,2))

  SIM <- SIM %>%
    mutate(CODUFOCOR = substring(CODMUNOCOR,1,2))

  SIM$CODUFNATU <- as.integer(SIM$CODUFNATU)

  SIM$CODMUNNATU <- as.integer(SIM$CODMUNNATU)

  SIM$CODUFRES <- as.integer(SIM$CODUFRES)

  SIM$CODMUNRES <- as.integer(SIM$CODMUNRES)

  SIM$CODUFOCOR <- as.integer(SIM$CODUFOCOR)

  SIM$CODMUNOCOR <- as.integer(SIM$CODMUNOCOR)

  SIM <- SIM %>%
    left_join(CID10%>% select(CID10, DESCR),by=join_by(TERM==CID10),keep = FALSE)

  SIM <- SIM %>%
    left_join(TABUF%>% select(SIGLA_UF,CODIGO),by=join_by(CODUFNATU==CODIGO),keep = F)

  SIM <- SIM %>%
    rename(UFNATU=SIGLA_UF)

  SIM <- SIM %>%
    left_join(TABUF%>% select(SIGLA_UF,CODIGO),by=join_by(CODUFRES==CODIGO),keep = F)

  SIM <- SIM %>%
    rename(UFRES=SIGLA_UF)

  SIM <- SIM %>%
    left_join(TABUF%>% select(SIGLA_UF,CODIGO),by=join_by(CODUFOCOR==CODIGO),keep = F)

  SIM <- SIM %>%
    rename(UFOCOR=SIGLA_UF)

  SIM <- SIM %>%
    left_join(CADMUN%>% select(MUNCOD,MUNNOMEX),by=join_by(CODMUNRES==MUNCOD),keep = F)

  SIM <- SIM %>%
    rename(MUNRES=MUNNOMEX)

  SIM <- SIM %>%
    left_join(CADMUN%>% select(MUNCOD,MUNNOMEX),by=join_by(CODMUNNATU==MUNCOD),keep = F)

  SIM <- SIM %>%
    rename(MUNNATU=MUNNOMEX)

  SIM <- SIM %>%
    left_join(CADMUN%>% select(MUNCOD,MUNNOMEX),by=join_by(CODMUNOCOR==MUNCOD),keep = F)

  SIM <- SIM %>%
    rename(MUNOCOR=MUNNOMEX)

  SIM <- SIM %>%
    left_join(ESTAB%>% select(CNES, FANTASIA),by=join_by(CODESTAB==CNES),keep = F)

  SIM <- SIM %>%
    rename(ESTAB=FANTASIA)

  SIM$OCUPMAE <- gsub("^0+","",SIM$OCUPMAE)

  SIM$OCUPMAE <- as.integer(SIM$OCUPMAE)

  SIM <- SIM %>%
    left_join(ocup,by=join_by(OCUPMAE==CODIGO),keep = F)


  SIM$TITULO <- ifelse(SIM$OCUPMAE=="999991","Estudante",
                       ifelse(SIM$OCUPMAE=="999992","Dona de Casa",
                              ifelse(SIM$OCUPMAE=="999993","Aposentada/Pensionista",
                                     ifelse(SIM$OCUPMAE=="999994","Desempregada",
                                            ifelse(SIM$OCUPMAE=="516115","Esteticista",
                                                   ifelse(SIM$OCUPMAE=="516135","Massagista",
                                                          ifelse(SIM$OCUPMAE=="514210","Faxineiro",
                                                                 ifelse(SIM$OCUPMAE=="422215","Recepcionista de seguro saúde",
                                                                        ifelse(SIM$OCUPMAE=="354110","Agenciador de propaganda",
                                                                               ifelse(SIM$OCUPMAE=="517315","Agente de segurança penitenciária",
                                                                                      ifelse(SIM$OCUPMAE=="510125","Chefe de cozinha",SIM$TITULO)))))))))))
  SIM <- SIM %>%
    rename(OCUPMAEDESC = TITULO)

  SIM$OCUP <- gsub("^0+","",SIM$OCUP)

  SIM$OCUP <- as.integer(SIM$OCUP)

  SIM <- SIM %>%
    left_join(ocup,by=join_by(OCUP==CODIGO),keep = F)


  SIM$TITULO <- ifelse(SIM$OCUP=="999991","Estudante",
                       ifelse(SIM$OCUP=="999992","Dona de Casa",
                              ifelse(SIM$OCUP=="999993","Aposentada/Pensionista",
                                     ifelse(SIM$OCUP=="999994","Desempregada",
                                            ifelse(SIM$OCUP=="516115","Esteticista",
                                                   ifelse(SIM$OCUP=="516135","Massagista",
                                                          ifelse(SIM$OCUP=="514210","Faxineiro",
                                                                 ifelse(SIM$OCUP=="422215","Recepcionista de seguro saúde",
                                                                        ifelse(SIM$OCUP=="354110","Agenciador de propaganda",
                                                                               ifelse(SIM$OCUP=="517315","Agente de segurança penitenciária",
                                                                                      ifelse(SIM$OCUP=="510125","Chefe de cozinha",SIM$TITULO)))))))))))
  SIM <- SIM %>%
    rename(OCUPDESC = TITULO, CAUSATERM=DESCR)

  SIM <- SIM %>%
    mutate(
      ANO=year(DTOBITO),MES_ANO=paste0(year(DTOBITO),"-",month(DTOBITO),"-","01")
    )

  SIM <- SIM %>%
    mutate(
      ANO=as.character(ANO),MES_ANO=as.Date(MES_ANO))

  SIM$UFNATU[is.na(SIM$UFNATU)]="Desconhecido"

  SIM$MUNNATU[is.na(SIM$MUNNATU)]="Desconhecido"

  SIM$MUNRES[is.na(SIM$MUNRES)]="Desconhecido"

  SIM$IDADEINT <- as.numeric(SIM$IDADEINT)

  SIM <- SIM %>%
    mutate(FAIXA_ETARIA = case_when(
      IDADEINT>=90 ~ "90 anos ou mais",
      IDADEINT>=1 & IDADEINT<5 ~ "01 a 04 anos",
      IDADEINT>=5 & IDADEINT<10 ~ "05 a 09 anos",
      IDADEINT>=10 & IDADEINT<15 ~ "10 a 14 anos",
      IDADEINT>=15 & IDADEINT<20 ~ "15 a 19 anos",
      IDADEINT>=20 & IDADEINT<25 ~ "20 a 24 anos",
      IDADEINT>=25 & IDADEINT<30 ~ "25 a 29 anos",
      IDADEINT>=30 & IDADEINT<35 ~ "30 a 34 anos",
      IDADEINT>=35 & IDADEINT<40 ~ "35 a 39 anos",
      IDADEINT>=40 & IDADEINT<45 ~ "40 a 44 anos",
      IDADEINT>=45 & IDADEINT<50 ~ "45 a 49 anos",
      IDADEINT>=50 & IDADEINT<55 ~ "50 a 54 anos",
      IDADEINT>=55 & IDADEINT<60 ~ "55 a 59 anos",
      IDADEINT>=60 & IDADEINT<65 ~ "60 a 64 anos",
      IDADEINT>=65 & IDADEINT<70 ~ "65 a 69 anos",
      IDADEINT>=70 & IDADEINT<75 ~ "70 a 74 anos",
      IDADEINT>=75 & IDADEINT<80 ~ "75 a 79 anos",
      IDADEINT>=80 & IDADEINT<85 ~ "80 a 84 anos",
      IDADEINT>=85 & IDADEINT<90 ~ "85 a 89 anos",
      IDADEINT<1 ~ "<1 ano"
    ))

  SIM <- SIM %>%
    mutate(FAIXA_ETARIA_MAE = case_when(
      IDADEMAE>=51 ~ "51 anos ou mais",
      IDADEMAE>=41 & IDADEMAE<51 ~ "41 a 50 anos",
      IDADEMAE>=31 & IDADEMAE<41 ~ "31 a 40 anos",
      IDADEMAE>=21 & IDADEMAE<31 ~ "21 a 30 anos",
      IDADEMAE>=15 & IDADEMAE<21 ~ "15 a 20 anos",
      IDADEMAE<15 ~ "menos de 15 anos"
    ))

  SIM <- SIM %>%
    mutate(FAIXA_PESO = case_when(
      PESO>=4000 ~ "4000g e mais",
      PESO>=3000 & PESO<4000 ~ "3000g a 3999g",
      PESO>=2500 & PESO<3000 ~ "2500g a 2999g",
      PESO>=1500 & PESO<2500 ~ "1500g a 2499g",
      PESO>=1000 & PESO<1500 ~ "1000g a 1499g",
      PESO<1000 ~ "0g a 999g"
    ))

  SIM <- SIM %>%
    mutate(COD_FAIXA_ETARIA_MAE=case_when(
      IDADEMAE>=51 ~ 6,
      IDADEMAE>=41 & IDADEMAE<51 ~ 5,
      IDADEMAE>=31 & IDADEMAE<41 ~ 4,
      IDADEMAE>=21 & IDADEMAE<31 ~ 3,
      IDADEMAE>=15 & IDADEMAE<21 ~ 2,
      IDADEMAE<15 ~ 1
    ))

  SIM <- SIM %>%
    mutate(COD_FAIXA_PESO = case_when(
      PESO>=4000 ~ 6,
      PESO>=3000 & PESO<4000 ~ 5,
      PESO>=2500 & PESO<3000 ~ 4,
      PESO>=1500 & PESO<2500 ~ 3,
      PESO>=1000 & PESO<1500 ~ 2,
      PESO<1000 ~ 1
    ))

  SIM <- SIM %>%
    mutate(COD_GESTACAO = case_when(
      GESTACAO=="Ignorado" ~ 7,
      GESTACAO=="42 semanas e mais" ~ 6,
      GESTACAO=="37 a 41 semanas" ~ 5,
      GESTACAO=="32 a 36 semanas" ~ 4,
      GESTACAO=="28 a 31 semanas" ~ 3,
      GESTACAO=="22 a 27 semanas" ~ 2,
      GESTACAO=="Menos de 22 semanas" ~ 1
    ))

  SIM <- SIM %>%
    mutate(COD_GRAVIDEZ = case_when(
      GRAVIDEZ=="Ignorado" ~ 4,
      GRAVIDEZ=="Tripla ou mais" ~ 3,
      GRAVIDEZ=="Dupla" ~ 2,
      GRAVIDEZ=="Única" ~ 1
    ))

  SIM <- SIM %>%
    mutate(COD_ESCOLARIDADE = case_when(
      ESC=="Ignorado" ~ 6,
      ESC=="12 e mais" ~ 5,
      ESC=="8 a 11 anos" ~ 4,
      ESC=="4 a 7 anos" ~ 3,
      ESC=="1 a 3 anos" ~ 2,
      ESC=="Nenhuma" ~ 1
    ))

  SIM <- SIM %>%
    mutate(COD_ESCOLARIDADE_MAE = case_when(
      ESCMAE=="Ignorado" ~ 6,
      ESCMAE=="12 e mais" ~ 5,
      ESCMAE=="8 a 11 anos" ~ 4,
      ESCMAE=="4 a 7 anos" ~ 3,
      ESCMAE=="1 a 3 anos" ~ 2,
      ESCMAE=="Nenhuma" ~ 1
    ))

  return(SIM)
}
